### PR TITLE
fix: created junction tables primary key

### PR DESCRIPTION
**Pull request by ms-si-Singh**

### CODE REVIEW

**Review by AndrewBB-BBD — COMMENTED** [review]
Nice spot! 
Can you change the ID to {Table name}_ID, and [int] to [INT], and add 'PRIMARY KEY' please?

**Comment by ms-si-Singh** [comment]
> @AndrewBB-BBD - please review the syntax now, I have edited it.

**Comment by AmyPegramBBD** [comment]
Are we going to have a specific ID for the junction table? Or I thought we were going to create a composite key?

**Review by AndrewBB-BBD — APPROVED** [review]

**Comment by ms-si-Singh** [comment]
> Are we going to have a specific ID for the junction table? Or I thought we were going to create a composite key?

Going to make it exactly as the example as the hive has it. Since we all understand the hive, in all fairness the PK in the junction tables will never be referenced to.

**Review by nikitasmal — APPROVED** [review]

**Comment by AndrewBB-BBD** [comment]
>
> > Are we going to have a specific ID for the junction table? Or I thought we were going to create a composite key?
> 
> Going to make it exactly as the example as the hive has it. Since we all understand the hive, in all fairness the PK in the junction tables will never be referenced to.

Might be difficult to justify having an unreferenced PK to Rudolph and co though. @AmyPegramBBD @nikitasmal @PhumzileNkosi @RiselleRawthee , thoughts?

**Review by AmyPegramBBD — APPROVED** [review]

**Pull request merged**
